export const ELIGIBILITY_SPEC_VERSION = 2;

export const MEMBERSHIP_FULL_BACKFILL_WATERMARK = `FULL_BACKFILL_V${ELIGIBILITY_SPEC_VERSION}`;

export const MEMBERSHIP_GRANT_BOUNDARY_WATERMARK = `GRANT_BOUNDARIES_V${ELIGIBILITY_SPEC_VERSION}`;

export const MEMBERSHIP_MISSING_PROFILE_SWEEP_WATERMARK = `MISSING_PROFILES_V${ELIGIBILITY_SPEC_VERSION}`;

export const MEMBERSHIP_DIRTY_REFRESH_QUEUE_NAME =
  'membership-refresh-dirty.fifo';

export const MEMBERSHIP_FULL_REFRESH_QUEUE_NAME =
  'membership-refresh-start.fifo';

export const MEMBERSHIP_DIRTY_REFRESH_MESSAGE_GROUP_ID =
  'membership-refresh-dirty';

export const MEMBERSHIP_DEFAULT_BATCH_SIZE = 25;
export const MEMBERSHIP_MAX_BATCH_SIZE = 100;
export const MEMBERSHIP_MAX_REFRESH_ATTEMPTS = 5;
export const MEMBERSHIP_MISSING_PROFILE_SWEEP_PAGE_SIZE = 1000;
