service: seizeApi

useDotenv: true

package:
  artifact: dist/index.zip
  individually: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 512
  timeout: 30

functions:
  seizeApi:
    handler: index.handler
    name: seizeApi
    environment:
      ACTIVATE_API_PASSWORD: false
      API_LOAD_SECRETS: true
      DB_HOST: ${env:DB_HOST}
      DB_HOST_READ: ${env:DB_HOST_READ}
      DB_NAME: ${env:DB_NAME}
      DB_PASS: ${env:DB_PASS}
      DB_PASS_READ: ${env:DB_PASS_READ}
      DB_PORT: ${env:DB_PORT}
      DB_USER: ${env:DB_USER}
      DB_USER_READ: ${env:DB_USER_READ}
      SENTRY_DSN: ${env:SENTRY_DSN}
      SEIZE_API_VERSION: ${env:SEIZE_API_VERSION}
      SENTRY_ENVIRONMENT: production
    events:
      - http:
          method: any
          path: /{any+}
          cors: true
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    vpc:
      securityGroupIds:
        - sg-033f6ed509ce4c3a4
        - sg-0b548abc33e4c84a3
      subnetIds:
        - subnet-08dbb020dea1a658d
        - subnet-003b0c8ce57cb67c2