insert into community_groups (id, name, created_at, created_by, visible, cic_min, cic_max, cic_user, cic_direction,
                              rep_min, rep_max, rep_user, rep_category, rep_direction, tdh_min, tdh_max, level_min,
                              level_max)
with st1 as (select id,
                    name,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.cic.min'))       as cic_min,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.cic.max'))       as cic_max,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.cic.user'))      as cic_user,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.cic.direction')) as cic_direction,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.rep.min'))       as rep_min,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.rep.max'))       as rep_max,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.rep.user'))      as rep_user,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.rep.direction')) as rep_direction,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.rep.category'))  as rep_category,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.tdh.min'))       as tdh_min,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.tdh.max'))       as tdh_max,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.tdh.min'))       as level_min,
                    JSON_UNQUOTE(JSON_EXTRACT(criteria, '$.tdh.max'))       as level_max,
                    created_at,
                    created_by,
                    visible
             from community_members_curation_criteria),
     st2 as (select id,
                         name,
                         created_at,
                         created_by,
                         visible,
                         IF(cic_min = 'null', null, CAST(cic_min as signed integer))     as cic_min,
                         IF(cic_max = 'null', null, CAST(cic_max as signed integer))     as cic_max,
                         IF(cic_user = 'null', null, cic_user)                           as cic_user,
                         IF(cic_direction = 'null', null, cic_direction)                 as cic_direction,
                         IF(rep_min = 'null', null, CAST(rep_min as signed integer))     as rep_min,
                         IF(rep_max = 'null', null, CAST(rep_max as signed integer))     as rep_max,
                         IF(rep_user = 'null', null, rep_user)                           as rep_user,
                         IF(rep_direction = 'null', null, rep_direction)                 as rep_direction,
                         IF(rep_category = 'null', null, rep_category)                   as rep_category,
                         IF(tdh_min = 'null', null, CAST(tdh_min as signed integer))     as tdh_min,
                         IF(tdh_max = 'null', null, CAST(tdh_max as signed integer))     as tdh_max,
                         IF(level_min = 'null', null, CAST(level_min as signed integer)) as level_min,
                         IF(level_max = 'null', null, CAST(level_max as signed integer)) as level_max
                  from st1),
     st3 as (select hr.id,
                       hr.name,
                       hr.created_at,
                       hr.created_by,
                       hr.visible,
                       hr.cic_min,
                       hr.cic_max,
                       (select external_id from profiles p where p.handle = hr.cic_user) as cic_user,
                       hr.cic_direction,
                       hr.rep_min,
                       hr.rep_max,
                       (select external_id from profiles p where p.handle = hr.rep_user) as rep_user,
                       hr.rep_direction,
                       hr.rep_category,
                       hr.tdh_min,
                       hr.tdh_max,
                       hr.level_min,
                       hr.level_max
                from st2 hr)
SELECT id,
       name,
       created_at,
       created_by,
       visible,
       cic_min,
       cic_max,
       cic_user,
       cic_direction,
       rep_min,
       rep_max,
       rep_user,
       rep_category,
       rep_direction,
       tdh_min,
       tdh_max,
       level_min,
       level_max
from st3 on duplicate key update community_groups.id = community_groups.id;