CREATE TABLE IF NOT EXISTS profile_cms_pointer_events (
  id varchar(100) NOT NULL,
  event_type varchar(25) NOT NULL,
  profile_id varchar(100) NOT NULL,
  profile_handle varchar(100) NOT NULL,
  package_db_id varchar(100) NOT NULL,
  package_id varchar(128) NOT NULL,
  package_version int NOT NULL,
  package_hash varchar(100) NOT NULL,
  payload_hash varchar(100) NOT NULL,
  previous_package_db_id varchar(100) DEFAULT NULL,
  actor_profile_id varchar(100) NOT NULL,
  signer_address varchar(42) DEFAULT NULL,
  signature text DEFAULT NULL,
  typed_data json DEFAULT NULL,
  typed_data_hash varchar(100) DEFAULT NULL,
  storage_receipt json DEFAULT NULL,
  event_sequence int NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (id),
  KEY idx_profile_cms_pointer_events_profile_created (profile_id, created_at, event_sequence),
  KEY idx_profile_cms_pointer_events_package (package_db_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
