CREATE TABLE IF NOT EXISTS profile_cms_packages (
  id varchar(100) NOT NULL,
  profile_id varchar(100) NOT NULL,
  profile_handle varchar(100) NOT NULL,
  package_id varchar(128) NOT NULL,
  version int NOT NULL,
  status varchar(25) NOT NULL,
  cms_package json NOT NULL,
  payload_hash varchar(100) NOT NULL,
  package_hash varchar(100) NOT NULL,
  primary_path varchar(512) NOT NULL,
  is_primary tinyint(1) NOT NULL DEFAULT 0,
  created_by_profile_id varchar(100) NOT NULL,
  published_by_profile_id varchar(100) DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  validated_at bigint DEFAULT NULL,
  published_at bigint DEFAULT NULL,
  failed_at bigint DEFAULT NULL,
  archived_at bigint DEFAULT NULL,
  superseded_by_id varchar(100) DEFAULT NULL,
  validation_result json DEFAULT NULL,
  validation_error text DEFAULT NULL,
  storage_receipts json NOT NULL,
  storage_provider varchar(25) DEFAULT NULL,
  storage_uri varchar(2048) DEFAULT NULL,
  storage_content_hash varchar(100) DEFAULT NULL,
  storage_provider_content_id varchar(255) DEFAULT NULL,
  storage_recorded_at varchar(64) DEFAULT NULL,
  storage_pinned tinyint(1) DEFAULT NULL,
  storage_canonical tinyint(1) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_profile_cms_packages_profile_state (profile_id, status),
  KEY idx_profile_cms_packages_profile_primary (profile_id, is_primary),
  KEY idx_profile_cms_packages_package_version (profile_id, package_id, version),
  KEY idx_profile_cms_packages_handle (profile_handle),
  KEY idx_profile_cms_packages_package_hash (package_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
