service: attachmentsProcessor

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

functions:
  attachmentsProcessor:
    handler: index.handler
    name: attachmentsProcessor
    description: ${env:VERSION_DESCRIPTION}
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    reservedConcurrency: 2
    events:
      - sqs:
          arn:
            Fn::GetAtt: [AttachmentsProcessingQueue, Arn]
          batchSize: 1
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: 'attachmentsProcessor_${opt:stage, self:provider.stage}'
      IPFS_API_ENDPOINT: ${env:IPFS_API_ENDPOINT}

resources:
  Resources:
    AttachmentsProcessorLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/attachmentsProcessor
        RetentionInDays: 60

    AttachmentsProcessingQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: attachments-processing
        VisibilityTimeout: 930
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [AttachmentsProcessingDLQ, Arn]
          maxReceiveCount: 10

    AttachmentsProcessingDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: attachments-processing-dlq

    AttachmentsProcessingQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: AttachmentsProcessingQueue
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS: arn:aws:iam::987989283142:role/lambda-vpc-role
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt AttachmentsProcessingQueue.Arn
