service: waveScoreRefreshLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

functions:
  waveScoreRefreshLoop:
    handler: index.handler
    reservedConcurrency: 1
    name: waveScoreRefreshLoop
    description: ${env:VERSION_DESCRIPTION}
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - WaveScoreRefreshStartQueue
              - Arn
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - WaveScoreDirtyRefreshQueue
              - Arn
      - schedule:
          rate: rate(1 minute)
          input:
            mode: 'DIRTY'
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: 'waveScoreRefreshLoop_${opt:stage, self:provider.stage}'

resources:
  Resources:
    WaveScoreRefreshLoopLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/waveScoreRefreshLoop
        RetentionInDays: 60

    WaveScoreRefreshStartQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'wave-score-refresh-start.fifo'
        FifoQueue: true
        VisibilityTimeout: 1000
        ContentBasedDeduplication: true
    WaveScoreDirtyRefreshQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'wave-score-refresh-dirty.fifo'
        FifoQueue: true
        VisibilityTimeout: 1000
        ContentBasedDeduplication: true
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [WaveScoreDirtyRefreshDLQ, Arn]
          maxReceiveCount: 5
    WaveScoreDirtyRefreshDLQ:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'wave-score-refresh-dirty-dlq.fifo'
        FifoQueue: true
        ContentBasedDeduplication: true
    WaveScoreRefreshTDHCalculatedSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):region}:987989283142:tdh-calculation-done.fifo
        Protocol: sqs
        Endpoint: !GetAtt
          - WaveScoreRefreshStartQueue
          - Arn
        RawMessageDelivery: true
    WaveScoreRefreshStartQueuePolicy:
      Type: 'AWS::SQS::QueuePolicy'
      Properties:
        Queues:
          - Ref: 'WaveScoreRefreshStartQueue'
        PolicyDocument:
          Statement:
            - Effect: 'Allow'
              Principal:
                Service: 'sns.amazonaws.com'
              Action:
                - sqs:SendMessage
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueUrl
                - sqs:GetQueueAttributes
                - sqs:ListQueueTags
                - sqs:ChangeMessageVisibility
              Resource:
                - !GetAtt WaveScoreRefreshStartQueue.Arn
    WaveScoreDirtyRefreshQueuePolicy:
      Type: 'AWS::SQS::QueuePolicy'
      Properties:
        Queues:
          - Ref: 'WaveScoreDirtyRefreshQueue'
        PolicyDocument:
          Statement:
            - Effect: 'Allow'
              Principal:
                AWS: arn:aws:iam::987989283142:role/lambda-vpc-role
              Action:
                - sqs:GetQueueUrl
                - sqs:SendMessage
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ChangeMessageVisibility
              Resource:
                - !GetAtt WaveScoreDirtyRefreshQueue.Arn
    WaveScoreDirtyRefreshDLQPolicy:
      Type: 'AWS::SQS::QueuePolicy'
      Properties:
        Queues:
          - Ref: 'WaveScoreDirtyRefreshDLQ'
        PolicyDocument:
          Statement:
            - Effect: 'Allow'
              Principal:
                AWS: arn:aws:iam::987989283142:role/lambda-vpc-role
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt WaveScoreDirtyRefreshDLQ.Arn
    WaveScoreRefreshLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      DependsOn:
        - WaveScoreRefreshLoopLogGroup
      Properties:
        LogGroupName:
          Ref: WaveScoreRefreshLoopLogGroup
        FilterPattern: 'Runtime.OutOfMemory'
        MetricTransformations:
          - MetricNamespace: 'Lambda/OOM'
            MetricName: 'waveScoreRefreshLoop_OOMErrorCount'
            MetricValue: '1'
            DefaultValue: 0

    WaveScoreRefreshLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: WaveScoreRefreshLoopOOMFilter
      Properties:
        AlarmName: !Sub '${AWS::StackName}-waveScoreRefreshLoop-OOM'
        AlarmDescription: !Sub 'Lambda waveScoreRefreshLoop OutOfMemory in ${AWS::Region}'
        Namespace: 'Lambda/OOM'
        MetricName: 'waveScoreRefreshLoop_OOMErrorCount'
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
