service: dummyLoop

package:
  artifact: dist/index.zip


plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    ALLOWLIST_AWS_REGION: "us-east-1"
  memorySize: 512
  timeout: 900

functions:
  dummyLoop:
    handler: index.handler
    name: dummyLoop
    events:
      - schedule:
          rate: rate(2 minutes)
          enabled: true
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    vpc:
      securityGroupIds:
        - sg-033f6ed509ce4c3a4
        - sg-0b548abc33e4c84a3
      subnetIds:
        - subnet-08dbb020dea1a658d
        - subnet-003b0c8ce57cb67c2