CREATE DATABASE IF NOT EXISTS OM6529;
CREATE USER IF NOT EXISTS '6529backend'@'%' IDENTIFIED WITH mysql_native_password BY 'backend9256';
ALTER USER '6529backend'@'%' IDENTIFIED WITH mysql_native_password BY 'backend9256';
GRANT ALL PRIVILEGES ON OM6529.* TO '6529backend'@'%';
FLUSH PRIVILEGES;