// This file is generated by scripts/generate-deploy-config.mjs.
// Edit config/deploy-services.json and rerun the generator instead.

export const GENERATED_DEPLOY_DEFAULT_ENVIRONMENT = 'staging' as const;

export const GENERATED_DEPLOY_DEFAULT_SERVICE = 'api' as const;

export const GENERATED_DEPLOY_SERVICE_CONFIGS = [
  {
    name: 'api',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'aggregatedActivityLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'artCurationNftWatchLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'cloudwatchAlarmsToDiscordLoop',
    allowed_environments: ['prod']
  },
  {
    name: 'claimsBuilder',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'claimsMediaArweaveUploader',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'customReplayLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'dbDumpsDaily',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'dbMigrationsLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'delegationsLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'discoverEnsLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'dropVideoConversionInvokerLoop',
    allowed_environments: ['staging']
  },
  {
    name: 'ethPriceLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'externalCollectionLiveTailingLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'externalCollectionSnapshottingLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'marketStatsLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'mediaResizerLoop',
    allowed_environments: ['prod']
  },
  {
    name: 'mintAnnouncementsLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'nextgenContractLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'nextgenMediaImageResolutions',
    allowed_environments: ['prod']
  },
  {
    name: 'nextgenMediaProxyInterceptor',
    allowed_environments: ['prod']
  },
  {
    name: 'nextgenMediaUploader',
    allowed_environments: ['prod']
  },
  {
    name: 'nextgenMetadataLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'nftHistoryLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'nftLinkRefresherLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'nftLinkMediaPreviewLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'nftOwnersLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'nftsLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'overRatesRevocationLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'ownersBalancesLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'populateHistoricConsolidatedTdh',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'pushNotificationsHandler',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'rateEventProcessingLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'refreshEnsLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'rememesLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'royaltiesLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 's3Uploader',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'subscriptionsDaily',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'subscriptionsTopUpLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'xTdhGrantsReviewerLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'tdhHistoryLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'tdhLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'teamLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'transactionsLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'transactionsProcessingLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'waveDecisionExecutionLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'waveLeaderboardSnapshotterLoop',
    allowed_environments: ['staging', 'prod']
  },
  {
    name: 'xTdhLoop',
    allowed_environments: ['staging', 'prod']
  }
] as const;
