export function renderDeployBusUI(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>6529 Release Bus</title><meta name="theme-color" content="#050505">
<style>
*{box-sizing:border-box}body{margin:0;background:#080808;color:#f4f4f5;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:16px}main{max-width:1180px;margin:auto;display:grid;gap:16px}header,.panel{border:1px solid #2d2d30;background:#111113;border-radius:16px;padding:20px}h1,h2,h3{margin:0 0 8px}h1{font-size:25px}h2{font-size:18px}h3{font-size:16px}.muted{color:#a1a1aa}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.field{display:grid;gap:6px}.wide{grid-column:1/-1}label{font-weight:650}input,select,textarea,button{font:inherit;border-radius:10px}input,select,textarea{width:100%;border:1px solid #3f3f46;background:#09090b;color:#fafafa;padding:10px 12px}input[type=checkbox]{width:auto}textarea{min-height:84px;resize:vertical}:focus-visible{outline:3px solid #60a5fa;outline-offset:2px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}button,a.button{border:1px solid #4b5563;background:#27272a;color:white;padding:9px 14px;text-decoration:none;cursor:pointer}button.primary{background:#2563eb;border-color:#3b82f6}button.danger{background:#7f1d1d;border-color:#ef4444}button:disabled{opacity:.5;cursor:not-allowed}.status{min-height:24px;margin-top:10px}.error{color:#fca5a5}.success{color:#86efac}.warning{color:#fde68a}.cards,.stack{display:grid;gap:10px}.card{border:1px solid #303036;background:#0b0b0d;border-radius:12px;padding:12px}.incident{border-color:#7f1d1d;background:#1c0b0b}.incident.info{border-color:#1d4ed8;background:#081225}.row{display:flex;gap:8px;justify-content:space-between;align-items:flex-start}.badge{border:1px solid #52525b;border-radius:999px;padding:2px 8px;font-size:12px;white-space:nowrap}.sha{font-family:ui-monospace,monospace;overflow-wrap:anywhere}.controls{display:flex;gap:8px;flex-wrap:wrap}.metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:10px 0}.metric{border:1px solid #27272a;border-radius:8px;padding:8px}.metric strong{display:block}.list{margin:6px 0;padding-left:20px}.timeline{border-left:2px solid #3f3f46;margin-left:8px;padding-left:14px}.timeline-item{margin:0 0 10px}.hidden{display:none!important}@media(max-width:720px){.grid,.metrics{grid-template-columns:1fr}.wide{grid-column:auto}.row{display:grid}}
</style></head><body><main>
<header><div class="row"><div><h1>Release Bus</h1><p class="muted">Queue an immutable branch SHA for staging, then production after staging evidence passes.</p></div><a class="button" href="/deploy/ui">Manual deploy console</a></div></header>
<section class="panel" aria-labelledby="auth-heading"><h2 id="auth-heading">GitHub authentication</h2><div class="grid"><div class="field wide"><label for="token">GitHub token</label><textarea id="token" autocomplete="off" spellcheck="false" placeholder="Token with repository access"></textarea></div></div><div class="actions"><button id="connect" class="primary" type="button">Connect</button><button id="forget" type="button">Forget token</button></div><div id="auth-status" class="status" role="status" aria-live="polite"></div></section>
<div id="authenticated" class="hidden">
<section class="panel" aria-labelledby="ready-heading"><h2 id="ready-heading">Mark exact SHA ready</h2><form id="ready-form"><div class="grid">
<div class="field"><label for="repository">Repository</label><select id="repository"><option value="frontend">Frontend</option><option value="backend">Backend</option></select></div>
<div class="field"><label for="lane">Target lane</label><select id="lane"><option value="STAGING">Staging</option><option value="PRODUCTION">Production</option></select></div>
<div class="field"><label for="branch">Branch</label><input id="branch" required pattern="[A-Za-z0-9._/-]+" placeholder="feature/example"></div>
<div class="field"><label for="sha">Exact head SHA</label><input id="sha" required pattern="[a-fA-F0-9]{40}" maxlength="40" class="sha" placeholder="40-character Git SHA"></div>
<div class="field wide"><label for="dependencies">Dependencies (optional)</label><textarea id="dependencies" placeholder="backend:feature/api-change&#10;frontend:feature/other"></textarea><span class="muted">One repository:branch dependency per line.</span></div>
<div id="frontend-gate-option" class="field wide"><label><input id="force-fresh-base-canary" type="checkbox"> Force a fresh frontend base canary</label><span class="muted">Bypasses reusable exact-SHA base evidence for the train containing this frontend candidate.</span></div>
<div id="backend-plan" class="wide hidden"><div class="grid"><div class="field"><label for="units">Backend deploy units</label><textarea id="units" placeholder="dbMigrationsLoop&#10;api"></textarea></div><div class="field"><label for="edges">Unit ordering</label><textarea id="edges" placeholder="dbMigrationsLoop -> api"></textarea></div></div></div>
</div><div class="actions"><button id="resolve" type="button">Resolve current SHA</button><button id="mark-ready" class="primary" type="submit" disabled>Mark ready</button></div><div id="ready-status" class="status" role="status" aria-live="polite"></div></form></section>
<section class="panel" aria-labelledby="queue-heading"><div class="row"><div><h2 id="queue-heading">Candidate queue</h2><p class="muted">Immutable candidates, holds, and validation state.</p></div><button id="refresh" type="button">Refresh</button></div><div id="candidates" class="cards"></div></section>
<section class="panel" aria-labelledby="active-train-heading"><h2 id="active-train-heading">Active train</h2><p class="muted">Current phase, exact wait, workflow progress, included candidates, and recovery evidence.</p><div id="active-train" class="stack" role="status" aria-live="polite"></div></section>
<section class="panel" aria-labelledby="trains-heading"><h2 id="trains-heading">Recent trains</h2><div id="trains" class="cards"></div><div id="train-details" class="stack"></div></section>
<section class="panel" aria-labelledby="controls-heading"><h2 id="controls-heading">Operator controls</h2><p class="muted">Pausing blocks the next irreversible operation; it does not terminate an AWS operation already in progress.</p><div id="controls" class="cards"></div><div class="field"><label for="control-reason">Audited reason</label><input id="control-reason" maxlength="1000" placeholder="Reason for pausing or resuming"></div><div class="controls actions"><button data-control="pause" data-scope="ALL" class="danger">Pause all</button><button data-control="pause" data-scope="STAGING">Pause staging</button><button data-control="pause" data-scope="PRODUCTION">Pause production</button><button data-control="resume" data-scope="ALL">Resume all</button><button data-control="resume" data-scope="STAGING">Resume staging</button><button data-control="resume" data-scope="PRODUCTION">Resume production</button></div><div id="control-status" class="status" role="status" aria-live="polite"></div></section>
</div></main><script src="/deploy/ui/bus/app.js" defer></script></body></html>`;
}

export function renderDeployBusUiApp(): string {
  return `'use strict';(function(){
var key='deploy-ui-token';var state={token:localStorage.getItem(key)||'',mode:'OFF'};
var byId=function(id){return document.getElementById(id)};
var auth=byId('authenticated'),token=byId('token'),authStatus=byId('auth-status'),readyStatus=byId('ready-status');
function status(node,message,error){node.textContent=message||'';node.className='status '+(error?'error':'success')}
function updateReadinessAvailability(){var lane=byId('lane').value;var allowed=state.mode==='SHADOW'||state.mode==='PRODUCTION'||(state.mode==='STAGING'&&lane==='STAGING');byId('mark-ready').disabled=!allowed;if(state.mode==='OFF'){status(readyStatus,'Release Bus is OFF. Use the manual deploy console.',true)}else if(state.mode==='STAGING'&&lane==='PRODUCTION'){status(readyStatus,'Production readiness is disabled while the bus is in STAGING mode.',true)}else if(state.mode==='SHADOW'){status(readyStatus,'SHADOW records decisions only; it does not stage or deploy this candidate.',false)}}
function headers(){return {'Authorization':'Bearer '+state.token,'Content-Type':'application/json'}}
async function request(url,options){var response=await fetch(url,Object.assign({},options||{},{headers:Object.assign({},headers(),(options&&options.headers)||{})}));var payload=await response.json().catch(function(){return{}});if(!response.ok)throw new Error(payload.error||payload.message||('Request failed ('+response.status+')'));return payload}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function safeActionUrl(value){var url=String(value||'');return new RegExp('^https://github[.]com/6529-Collections/6529seize-(?:frontend|backend)/actions/runs/[0-9]+$').test(url)?url:''}
function evidenceUrl(reason){var match=String(reason||'').match(new RegExp('https://github[.]com/6529-Collections/6529seize-(?:frontend|backend)/actions/runs/[0-9]+'));return match?safeActionUrl(match[0]):''}
function formatDuration(value){var ms=Math.max(0,Number(value)||0),seconds=Math.floor(ms/1000),minutes=Math.floor(seconds/60),hours=Math.floor(minutes/60);if(hours)return hours+'h '+(minutes%60)+'m';if(minutes)return minutes+'m '+(seconds%60)+'s';return seconds+'s'}
function formatTime(value){var number=Number(value);return number?new Date(number).toLocaleString():'Not recorded'}
function workflowLink(operation){var url=safeActionUrl(operation&&operation.workflow_url);return url?'<a class="button" href="'+esc(url)+'" target="_blank" rel="noreferrer">Open GitHub Actions run</a>':''}
function renderStringList(items,empty){return Array.isArray(items)&&items.length?'<ul class="list">'+items.map(function(item){return '<li>'+esc(typeof item==='object'?(item.suite+' — '+item.test):item)+'</li>'}).join('')+'</ul>':'<p class="muted">'+esc(empty)+'</p>'}
function parseDependencies(){return byId('dependencies').value.split(/\\n/).map(function(v){return v.trim()}).filter(Boolean).map(function(line){var index=line.indexOf(':');if(index<1)throw new Error('Dependency must be repository:branch');return{repository:line.slice(0,index),branch:line.slice(index+1)}})}
function parsePlan(){if(byId('repository').value!=='backend')return null;var units=byId('units').value.split(/\\n|,/).map(function(v){return v.trim()}).filter(Boolean);var edges=byId('edges').value.split(/\\n/).map(function(v){return v.trim()}).filter(Boolean).map(function(line){var values=line.split(/\\s*->\\s*/);if(values.length!==2)throw new Error('Unit edge must use A -> B');return values});return{units:units,edges:edges}}
async function connect(){state.token=(token.value||state.token).trim();if(!state.token){status(authStatus,'Paste a token first.',true);return}try{var data=await request('/deploy/ui/session');localStorage.setItem(key,state.token);token.value='';auth.classList.remove('hidden');status(authStatus,'Authenticated as '+data.login,false);await refresh()}catch(error){state.token='';status(authStatus,error.message,true)}}
async function refresh(){var results=await Promise.all([request('/deploy/release-candidates?limit=100'),request('/deploy/release-trains'),request('/deploy/release-bus/controls')]);renderCandidates(results[0].candidates||[]);renderTrains(results[1].trains||[]);renderOverview(byId('active-train'),results[1].active_train);renderControls(results[2].controls||[],results[2].mode)}
function candidateHeadNotice(item){if(item.head_relation==='SUPERSEDED_BY_UNREGISTERED_HEAD')return '<div class="error">Historical immutable SHA. Branch moved to unregistered head <span class="sha">'+esc(item.unregistered_branch_head_sha||'unknown')+'</span>; resolve and mark that head ready separately.</div>';if(item.head_relation==='BRANCH_DELETED')return '<div class="error">Historical immutable SHA; the source branch was deleted.</div>';if(item.head_relation==='VALIDATED_IMMUTABLE_SHA')return '<div class="info">Staging validation applies only to this exact immutable SHA. Resolve the branch again before production readiness.</div>';return '<div class="muted">Readiness is bound to this exact immutable SHA.</div>'}
function renderCandidates(items){byId('candidates').innerHTML=items.length?items.map(function(item){var cancellable=!['SUPERSEDED','PRODUCTION_VALIDATED','CANCELLED'].includes(item.status);return '<article class="card"><div class="row"><div><strong>'+esc(item.repository)+' / '+esc(item.branch_name)+'</strong><div class="sha">'+esc(item.immutable_head_sha||item.head_sha)+'</div><div class="muted">'+esc(item.hold_reason||'No hold')+'</div>'+candidateHeadNotice(item)+(item.force_fresh_base_canary?'<div class="warning">Fresh base canary required</div>':'')+'</div><div><span class="badge">'+esc(item.status)+'</span>'+(cancellable?' <button type="button" data-cancel="'+esc(item.id)+'">Cancel</button>':'')+'</div></div></article>'}).join(''):'<p class="muted">No candidates yet.</p>';Array.prototype.forEach.call(document.querySelectorAll('[data-cancel]'),function(button){button.addEventListener('click',async function(){try{await request('/deploy/release-candidates/'+encodeURIComponent(button.dataset.cancel)+'/cancel',{method:'POST',body:'{}'});await refresh()}catch(error){status(readyStatus,error.message,true)}})})}
function renderOperation(operation){if(!operation)return '<div class="card"><p class="muted">No active operation.</p></div>';var progress=operation.active_job||operation.active_step?'<div><strong>Active workflow progress</strong><div>'+esc(operation.active_job||'Job unavailable')+' / '+esc(operation.active_step||'Step unavailable')+'</div></div>':'';var failure=operation.failed_job||operation.failed_step?'<div class="error"><strong>Failed at</strong><div>'+esc(operation.failed_job||'Job unavailable')+' / '+esc(operation.failed_step||'Step unavailable')+'</div></div>':'';return '<article class="card"><div class="row"><div><strong>'+esc(operation.phase)+' · '+esc(operation.operation_type)+'</strong><div class="muted">'+esc(operation.repository||'orchestration')+' / '+esc(operation.environment||'orchestration')+(operation.service?' / '+esc(operation.service):'')+'</div></div><span class="badge">'+esc(operation.health)+'</span></div><div class="metrics"><div class="metric"><span class="muted">Elapsed</span><strong>'+esc(formatDuration(operation.elapsed_ms))+'</strong></div><div class="metric"><span class="muted">Run ID</span><strong>'+esc(operation.run_id||'Discovering')+'</strong></div><div class="metric"><span class="muted">Last progress</span><strong>'+esc(formatTime(operation.last_progress_at||operation.updated_at))+'</strong></div></div><div class="sha">Expected SHA '+esc(operation.expected_sha||'not applicable')+'</div>'+progress+failure+(operation.stalled_reason?'<p class="warning">Stalled reason: '+esc(operation.stalled_reason)+'</p>':'')+'<div class="actions">'+workflowLink(operation)+'</div></article>'}
function renderBackendEvidence(value){if(!value)return '';var tests=value.tests||{};return '<article class="card"><div class="row"><div><h3>Backend exact-tree preflight</h3><p>Validation '+esc(value.execution||'unknown')+'; '+esc(value.reuse_reason||'reason unavailable')+'.</p></div><span class="badge">EXECUTED</span></div><div class="sha">Source '+esc(value.source_sha||'unknown')+' · tree '+esc(value.source_tree||'unknown')+'</div><div class="metrics"><div class="metric"><span class="muted">Test files</span><strong>'+esc(String(tests.executed_files||0))+'/'+esc(String(tests.expected_files||0))+'</strong></div><div class="metric"><span class="muted">Tests</span><strong>'+esc(String(tests.total_tests||0))+'</strong></div><div class="metric"><span class="muted">Unit builds</span><strong>'+esc(String(value.package_build_count||0))+'</strong></div></div><div class="sha">Artifact '+esc(value.artifact_digest||'unavailable')+'</div></article>'}
function renderBackendDeploy(value){if(!value)return '';var layers=(value.layers||[]).map(function(layer,index){return '<li>Layer '+(index+1)+': '+esc((layer||[]).join(', ')||'empty')+'</li>'}).join('');return '<article class="card"><div class="row"><div><h3>Backend deployment DAG</h3><p>Dependency layers control order; listing units alone does not.</p></div><span class="badge">CONCURRENCY '+esc(String(value.concurrency||1))+'</span></div><p><strong>Active frontier:</strong> '+esc((value.active_services||value.frontier||[]).join(', ')||'none')+'</p><ul class="list">'+layers+'</ul><p><strong>Succeeded:</strong> '+esc((value.succeeded_services||[]).join(', ')||'none')+'</p><p><strong>Failed:</strong> '+esc((value.failed_services||[]).join(', ')||'none')+'</p></article>'}
function renderActiveOperations(items){return Array.isArray(items)&&items.length>1?'<article class="card"><h3>Concurrently active operations</h3>'+items.map(function(item){return '<div class="row"><span>'+esc(item.operation_type)+(item.service?' · '+esc(item.service):'')+'</span><span class="badge">'+esc(item.status)+'</span></div>'}).join('')+'</article>':''}
function renderIncident(incident){if(!incident)return '';var kind=incident.severity==='INFO'?' info':'';var dispositions=(incident.candidate_dispositions||[]).map(function(item){return '<li>'+esc(item.id)+' · '+esc(item.status)+(item.hold_reason?' · '+esc(item.hold_reason):'')+'</li>'}).join('');return '<article class="card incident'+kind+'"><div class="row"><div><h3>'+esc(incident.title)+'</h3><p>'+esc(incident.summary)+'</p></div><span class="badge">'+esc(incident.attribution)+'</span></div>'+(incident.phase?'<p><strong>Failure phase:</strong> '+esc(incident.phase)+'</p>':'')+(incident.retry_state?'<p><strong>Retry state:</strong> '+esc(incident.retry_state)+'</p>':'')+(incident.failed_gate?'<p><strong>Failed gate:</strong> '+esc(incident.failed_gate)+'</p>':'')+(incident.failed_job||incident.failed_step?'<p><strong>Workflow failure:</strong> '+esc(incident.failed_job||'job unavailable')+' / '+esc(incident.failed_step||'step unavailable')+'</p>':'')+'<h3>Failing suites</h3>'+renderStringList(incident.failing_suites,'No structured failing suite was reported.')+'<h3>Failing tests</h3>'+renderStringList(incident.failing_tests,'No structured failing test was reported.')+'<p><strong>Returned candidates:</strong> '+esc((incident.returned_candidates||[]).join(', ')||'None')+'</p><p><strong>Quarantined candidates:</strong> '+esc((incident.quarantined_candidates||[]).join(', ')||'None')+'</p>'+(dispositions?'<h3>Candidate disposition</h3><ul class="list">'+dispositions+'</ul>':'')+'<p><strong>Recommended recovery:</strong> '+esc(incident.recommended_recovery)+'</p></article>'}
function renderIncludedCandidates(items){return '<article class="card"><h3>Included candidates</h3>'+(Array.isArray(items)&&items.length?items.map(function(item){var progress=item.active_job||item.active_step?(item.active_job||'Job unavailable')+' / '+(item.active_step||'Step unavailable'):item.operation_type||'Waiting for the next operation';return '<div class="row"><div><strong>'+esc(item.repository||'unknown')+' / '+esc(item.branch_name||item.id)+'</strong><div class="sha">'+esc(item.head_sha||'SHA unavailable')+'</div><div>'+esc(item.current_phase||'Phase unavailable')+' · '+esc(progress)+'</div><div class="muted">Lifecycle '+esc(item.lifecycle_status||item.status||item.item_status)+(item.hold_reason||item.item_hold_reason?' · '+esc(item.hold_reason||item.item_hold_reason):'')+'</div></div><span class="badge">'+esc(item.phase_state||item.current_phase||item.status||item.item_status)+'</span></div>'}).join(''):'<p class="muted">No candidates are included in this train.</p>')+'</article>'}
function renderTimeline(items){return '<article class="card"><h3>Train timeline</h3><div class="timeline">'+(Array.isArray(items)&&items.length?items.map(function(item){var detail=item.reason||item.operation_type||item.operation_key||item.status||item.phase||'';var progress=item.active_job||item.failed_job?(item.active_job||item.failed_job)+' / '+(item.active_step||item.failed_step||'step unavailable'):'';return '<div class="timeline-item"><strong>'+esc(item.event_type)+'</strong><div class="muted">'+esc(formatTime(item.created_at))+(detail?' · '+esc(detail):'')+'</div>'+(progress?'<div>'+esc(progress)+'</div>':'')+'</div>'}).join(''):'<p class="muted">No durable events have been recorded.</p>')+'</div></article>'}
function renderBaseEvidence(value){if(!value)return '';var link=safeActionUrl(value.evidence_uri);var promotion=value.promotion?'<p><strong>Carry-forward promotion:</strong> '+esc(value.promotion.status)+' · '+esc(value.promotion.reason||'No reason recorded')+'</p>'+(value.promotion.final_sha?'<div class="sha">Final SHA '+esc(value.promotion.final_sha)+'</div>':'')+(value.promotion.proof_digest?'<div class="sha">Proof digest '+esc(value.promotion.proof_digest)+'</div>':''):'';return '<article class="card"><div class="row"><div><h3>Base canary evidence</h3><p>'+esc(value.summary)+'</p></div><span class="badge">'+esc(value.decision)+'</span></div>'+(value.source_train_id?'<p><strong>Source train:</strong> '+esc(value.source_train_id)+'</p>':'')+(value.source_run_id?'<p><strong>Source run:</strong> '+esc(value.source_run_id)+'</p>':'')+(value.source_artifact_digest?'<div class="sha">Artifact digest '+esc(value.source_artifact_digest)+'</div>':'')+promotion+(link?'<div class="actions"><a class="button" href="'+esc(link)+'" target="_blank" rel="noreferrer">Open source evidence</a></div>':'')+'</article>'}
function renderOverview(node,train){if(!train){node.innerHTML='<p class="muted">No active train.</p>';return}var wait=train.wait_reason?'<article class="card"><h3>Current wait</h3><p>'+esc(train.wait_reason.summary)+'</p><span class="badge">'+esc(train.wait_reason.code)+'</span>'+(train.wait_reason.lease?'<div class="metrics"><div class="metric"><span class="muted">Lease owner</span><strong>'+esc(train.wait_reason.lease.owner||'unowned')+'</strong></div><div class="metric"><span class="muted">Heartbeat</span><strong>'+esc(formatTime(train.wait_reason.lease.heartbeat_at))+'</strong></div><div class="metric"><span class="muted">Expiry</span><strong>'+esc(formatTime(train.wait_reason.lease.expires_at))+'</strong></div></div>':'')+'</article>':'';node.innerHTML='<article class="card"><div class="row"><div><h3>'+esc(train.target_lane)+' train · '+esc(train.phase)+'</h3><div class="sha">'+esc(train.id)+' · revision '+esc(train.revision)+'</div></div><span class="badge">'+esc(train.phase_state)+'</span></div><div class="metrics"><div class="metric"><span class="muted">Train elapsed</span><strong>'+esc(formatDuration(train.elapsed_ms))+'</strong></div><div class="metric"><span class="muted">Worker heartbeat</span><strong>'+esc(formatTime(train.latest_worker_heartbeat_at))+'</strong></div><div class="metric"><span class="muted">Last event</span><strong>'+esc(train.last_progress_event?formatTime(train.last_progress_event.created_at):'Not recorded')+'</strong></div></div></article>'+renderIncident(train.incident)+renderBaseEvidence(train.base_evidence)+renderBackendEvidence(train.backend_preflight_evidence)+renderBackendDeploy(train.backend_deploy)+wait+renderActiveOperations(train.active_operations)+renderOperation(train.current_operation)+renderIncludedCandidates(train.included_candidates)+renderTimeline(train.timeline)}
function renderTrains(items){byId('trains').innerHTML=items.length?items.map(function(item){return '<article class="card"><div class="row"><div><strong>'+esc(item.target_lane)+' train</strong><div class="sha">'+esc(item.id)+' · revision '+esc(item.revision)+'</div></div><div><span class="badge">'+esc(item.status)+'</span> <button type="button" data-train="'+esc(item.id)+'">Details</button></div></div></article>'}).join(''):'<p class="muted">No trains yet.</p>';Array.prototype.forEach.call(document.querySelectorAll('[data-train]'),function(button){button.addEventListener('click',async function(){var node=byId('train-details');node.innerHTML='<p class="muted">Loading train details…</p>';try{var data=await request('/deploy/release-trains/'+encodeURIComponent(button.dataset.train));renderOverview(node,data.overview)}catch(error){node.innerHTML='<p class="error">'+esc(error.message)+'</p>'}})})}
function renderControls(items,mode){state.mode=mode;byId('controls').innerHTML='<p><span class="badge">Mode '+esc(mode)+'</span></p>'+items.map(function(item){var url=item.github_actor==='release-bus-worker'?evidenceUrl(item.reason):'';var details=item.reason?'<div class="muted">'+esc(item.reason)+'</div>':'';if(item.github_actor){details+='<div class="muted">Updated by '+esc(item.github_actor)+'</div>'}if(url){details+='<div><a class="button" href="'+esc(url)+'" target="_blank" rel="noreferrer">Open failure evidence</a></div>'}return '<div class="card"><div class="row"><strong>'+esc(item.scope)+'</strong><span class="badge">'+(item.paused?'PAUSED':'RUNNING')+'</span></div>'+details+'</div>'}).join('');updateReadinessAvailability()}
byId('connect').addEventListener('click',connect);byId('forget').addEventListener('click',function(){localStorage.removeItem(key);state.token='';auth.classList.add('hidden');token.value='';status(authStatus,'Token removed.',false)});byId('repository').addEventListener('change',function(){var backend=byId('repository').value==='backend';byId('backend-plan').classList.toggle('hidden',!backend);byId('frontend-gate-option').classList.toggle('hidden',backend);if(backend)byId('force-fresh-base-canary').checked=false});byId('lane').addEventListener('change',updateReadinessAvailability);
byId('resolve').addEventListener('click',async function(){try{var repo=byId('repository').value,branch=byId('branch').value.trim();if(!branch)throw new Error('Enter a branch first');var data=await request('/deploy/ui/branch-head?repository='+encodeURIComponent(repo)+'&branch='+encodeURIComponent(branch));byId('sha').value=data.head_sha;status(readyStatus,'Resolved '+data.head_sha,false)}catch(error){status(readyStatus,error.message,true)}});
byId('ready-form').addEventListener('submit',async function(event){event.preventDefault();try{var body={repository:byId('repository').value,branch:byId('branch').value.trim(),expected_head_sha:byId('sha').value.trim(),target_lane:byId('lane').value,dependencies:parseDependencies(),deploy_plan:parsePlan(),force_fresh_base_canary:byId('repository').value==='frontend'&&byId('force-fresh-base-canary').checked};var data=await request('/deploy/release-candidates/ready',{method:'POST',body:JSON.stringify(body)});status(readyStatus,'Queued '+data.candidate.repository+' '+data.candidate.head_sha,false);await refresh()}catch(error){status(readyStatus,error.message,true)}});
byId('refresh').addEventListener('click',function(){refresh().catch(function(error){status(readyStatus,error.message,true)})});Array.prototype.forEach.call(document.querySelectorAll('[data-control]'),function(button){button.addEventListener('click',async function(){try{var reason=byId('control-reason').value.trim();if(reason.length<3)throw new Error('Enter an audited reason');var action=button.dataset.control;await request('/deploy/release-bus/'+action,{method:'POST',body:JSON.stringify({scope:button.dataset.scope,reason:reason})});status(byId('control-status'),'Control updated.',false);await refresh()}catch(error){status(byId('control-status'),error.message,true)}})});
if(state.token){connect()}else{status(authStatus,'Paste a GitHub token to continue.',false)}
})();`;
}
