export function renderDeployBusUI(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>6529 Release Bus</title><meta name="theme-color" content="#050505">
<style>
*{box-sizing:border-box}body{margin:0;background:#080808;color:#f4f4f5;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:16px}main{max-width:1180px;margin:auto;display:grid;gap:16px}header,.panel{border:1px solid #2d2d30;background:#111113;border-radius:16px;padding:20px}h1,h2{margin:0 0 8px}h1{font-size:25px}h2{font-size:18px}.muted{color:#a1a1aa}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.field{display:grid;gap:6px}.wide{grid-column:1/-1}label{font-weight:650}input,select,textarea,button{font:inherit;border-radius:10px}input,select,textarea{width:100%;border:1px solid #3f3f46;background:#09090b;color:#fafafa;padding:10px 12px}textarea{min-height:84px;resize:vertical}:focus-visible{outline:3px solid #60a5fa;outline-offset:2px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}button,a.button{border:1px solid #4b5563;background:#27272a;color:white;padding:9px 14px;text-decoration:none;cursor:pointer}button.primary{background:#2563eb;border-color:#3b82f6}button.danger{background:#7f1d1d;border-color:#ef4444}button:disabled{opacity:.5;cursor:not-allowed}.status{min-height:24px;margin-top:10px}.error{color:#fca5a5}.success{color:#86efac}.cards{display:grid;gap:10px}.card{border:1px solid #303036;background:#0b0b0d;border-radius:12px;padding:12px}.row{display:flex;gap:8px;justify-content:space-between;align-items:flex-start}.badge{border:1px solid #52525b;border-radius:999px;padding:2px 8px;font-size:12px;white-space:nowrap}.sha{font-family:ui-monospace,monospace;overflow-wrap:anywhere}.controls{display:flex;gap:8px;flex-wrap:wrap}.hidden{display:none!important}@media(max-width:720px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.row{display:grid}}
</style></head><body><main>
<header><div class="row"><div><h1>Release Bus</h1><p class="muted">Queue an immutable branch SHA for staging, then production after staging evidence passes.</p></div><a class="button" href="/deploy/ui">Manual deploy console</a></div></header>
<section class="panel" aria-labelledby="auth-heading"><h2 id="auth-heading">GitHub authentication</h2><div class="grid"><div class="field wide"><label for="token">GitHub token</label><textarea id="token" autocomplete="off" spellcheck="false" placeholder="Token with repository access"></textarea></div></div><div class="actions"><button id="connect" class="primary" type="button">Connect</button><button id="forget" type="button">Forget token</button></div><div id="auth-status" class="status" role="status" aria-live="polite"></div></section>
<div id="authenticated" class="hidden">
<section class="panel" aria-labelledby="ready-heading"><h2 id="ready-heading">Mark exact SHA ready</h2><form id="ready-form"><div class="grid">
<div class="field"><label for="repository">Repository</label><select id="repository"><option value="frontend">Frontend</option><option value="backend">Backend</option></select></div>
<div class="field"><label for="lane">Target lane</label><select id="lane"><option value="STAGING">Staging</option><option value="PRODUCTION">Production</option></select></div>
<div class="field"><label for="branch">Branch</label><input id="branch" required pattern="[A-Za-z0-9._/-]+" placeholder="feature/example"></div>
<div class="field"><label for="sha">Exact head SHA</label><input id="sha" required pattern="[a-fA-F0-9]{40}" maxlength="40" class="sha" placeholder="40-character Git SHA"></div>
<div class="field wide"><label for="dependencies">Dependencies (optional)</label><textarea id="dependencies" placeholder="backend:feature/api-change&#10;frontend:feature/other"></textarea><span class="muted">One repository:branch dependency per line.</span></div>
<div id="backend-plan" class="wide hidden"><div class="grid"><div class="field"><label for="units">Backend deploy units</label><textarea id="units" placeholder="dbMigrationsLoop&#10;api"></textarea></div><div class="field"><label for="edges">Unit ordering</label><textarea id="edges" placeholder="dbMigrationsLoop -> api"></textarea></div></div></div>
</div><div class="actions"><button id="resolve" type="button">Resolve current SHA</button><button id="mark-ready" class="primary" type="submit" disabled>Mark ready</button></div><div id="ready-status" class="status" role="status" aria-live="polite"></div></form></section>
<section class="panel" aria-labelledby="queue-heading"><div class="row"><div><h2 id="queue-heading">Candidate queue</h2><p class="muted">Immutable candidates, holds, and validation state.</p></div><button id="refresh" type="button">Refresh</button></div><div id="candidates" class="cards"></div></section>
<section class="panel" aria-labelledby="trains-heading"><h2 id="trains-heading">Recent trains</h2><div id="trains" class="cards"></div></section>
<section class="panel" aria-labelledby="controls-heading"><h2 id="controls-heading">Operator controls</h2><p class="muted">Pausing blocks the next irreversible operation; it does not terminate an AWS operation already in progress.</p><div id="controls" class="cards"></div><div class="field"><label for="control-reason">Audited reason</label><input id="control-reason" maxlength="1000" placeholder="Reason for pausing or resuming"></div><div class="controls actions"><button data-control="pause" data-scope="ALL" class="danger">Pause all</button><button data-control="pause" data-scope="STAGING">Pause staging</button><button data-control="pause" data-scope="PRODUCTION">Pause production</button><button data-control="resume" data-scope="ALL">Resume all</button><button data-control="resume" data-scope="STAGING">Resume staging</button><button data-control="resume" data-scope="PRODUCTION">Resume production</button></div><div id="control-status" class="status" role="status" aria-live="polite"></div></section>
</div></main><script src="/deploy/ui/bus/app.js" defer></script></body></html>`;
}

export function renderDeployBusUiApp(): string {
  return `'use strict';(function(){
var key='deploy-ui-token';var state={token:localStorage.getItem(key)||'',mode:'OFF'};
var byId=function(id){return document.getElementById(id)};
var auth=byId('authenticated'),token=byId('token'),authStatus=byId('auth-status'),readyStatus=byId('ready-status');
function status(node,message,error){node.textContent=message||'';node.className='status '+(error?'error':'success')}
function updateReadinessAvailability(){var lane=byId('lane').value;var allowed=state.mode==='SHADOW'||state.mode==='PRODUCTION'||(state.mode==='STAGING'&&lane==='STAGING');byId('mark-ready').disabled=!allowed;if(state.mode==='OFF'){status(readyStatus,'Release Bus is OFF. Use the manual deploy console.',true)}else if(state.mode==='STAGING'&&lane==='PRODUCTION'){status(readyStatus,'Production readiness is disabled while the bus is in STAGING mode.',true)}else if(state.mode==='SHADOW'){status(readyStatus,'SHADOW records decisions only; it does not stage or deploy this candidate.',false)}}
function headers(){return {'Authorization':'Bearer '+state.token,'Content-Type':'application/json'}}
async function request(url,options){var response=await fetch(url,Object.assign({},options||{},{headers:Object.assign({},headers(),(options&&options.headers)||{})}));var payload=await response.json().catch(function(){return{}});if(!response.ok)throw new Error(payload.error||payload.message||('Request failed ('+response.status+')'));return payload}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function parseDependencies(){return byId('dependencies').value.split(/\\n/).map(function(v){return v.trim()}).filter(Boolean).map(function(line){var index=line.indexOf(':');if(index<1)throw new Error('Dependency must be repository:branch');return{repository:line.slice(0,index),branch:line.slice(index+1)}})}
function parsePlan(){if(byId('repository').value!=='backend')return null;var units=byId('units').value.split(/\\n|,/).map(function(v){return v.trim()}).filter(Boolean);var edges=byId('edges').value.split(/\\n/).map(function(v){return v.trim()}).filter(Boolean).map(function(line){var values=line.split(/\\s*->\\s*/);if(values.length!==2)throw new Error('Unit edge must use A -> B');return values});return{units:units,edges:edges}}
async function connect(){state.token=(token.value||state.token).trim();if(!state.token){status(authStatus,'Paste a token first.',true);return}try{var data=await request('/deploy/ui/session');localStorage.setItem(key,state.token);token.value='';auth.classList.remove('hidden');status(authStatus,'Authenticated as '+data.login,false);await refresh()}catch(error){state.token='';status(authStatus,error.message,true)}}
async function refresh(){var results=await Promise.all([request('/deploy/release-candidates?limit=100'),request('/deploy/release-trains'),request('/deploy/release-bus/controls')]);renderCandidates(results[0].candidates||[]);renderTrains(results[1].trains||[]);renderControls(results[2].controls||[],results[2].mode)}
function renderCandidates(items){byId('candidates').innerHTML=items.length?items.map(function(item){return '<article class="card"><div class="row"><div><strong>'+esc(item.repository)+' / '+esc(item.branch_name)+'</strong><div class="sha">'+esc(item.head_sha)+'</div><div class="muted">'+esc(item.hold_reason||'No hold')+'</div></div><div><span class="badge">'+esc(item.status)+'</span> <button type="button" data-cancel="'+esc(item.id)+'">Cancel</button></div></div></article>'}).join(''):'<p class="muted">No candidates yet.</p>';Array.prototype.forEach.call(document.querySelectorAll('[data-cancel]'),function(button){button.addEventListener('click',async function(){try{await request('/deploy/release-candidates/'+encodeURIComponent(button.dataset.cancel)+'/cancel',{method:'POST',body:'{}'});await refresh()}catch(error){status(readyStatus,error.message,true)}})})}
function renderTrains(items){byId('trains').innerHTML=items.length?items.map(function(item){return '<article class="card"><div class="row"><div><strong>'+esc(item.target_lane)+' train</strong><div class="sha">'+esc(item.id)+' · revision '+esc(item.revision)+'</div></div><span class="badge">'+esc(item.status)+'</span></div></article>'}).join(''):'<p class="muted">No trains yet.</p>'}
function renderControls(items,mode){state.mode=mode;byId('controls').innerHTML='<p><span class="badge">Mode '+esc(mode)+'</span></p>'+items.map(function(item){return '<div class="card row"><strong>'+esc(item.scope)+'</strong><span class="badge">'+(item.paused?'PAUSED':'RUNNING')+'</span></div>'}).join('');updateReadinessAvailability()}
byId('connect').addEventListener('click',connect);byId('forget').addEventListener('click',function(){localStorage.removeItem(key);state.token='';auth.classList.add('hidden');token.value='';status(authStatus,'Token removed.',false)});byId('repository').addEventListener('change',function(){byId('backend-plan').classList.toggle('hidden',byId('repository').value!=='backend')});byId('lane').addEventListener('change',updateReadinessAvailability);
byId('resolve').addEventListener('click',async function(){try{var repo=byId('repository').value,branch=byId('branch').value.trim();if(!branch)throw new Error('Enter a branch first');var data=await request('/deploy/ui/branch-head?repository='+encodeURIComponent(repo)+'&branch='+encodeURIComponent(branch));byId('sha').value=data.head_sha;status(readyStatus,'Resolved '+data.head_sha,false)}catch(error){status(readyStatus,error.message,true)}});
byId('ready-form').addEventListener('submit',async function(event){event.preventDefault();try{var body={repository:byId('repository').value,branch:byId('branch').value.trim(),expected_head_sha:byId('sha').value.trim(),target_lane:byId('lane').value,dependencies:parseDependencies(),deploy_plan:parsePlan()};var data=await request('/deploy/release-candidates/ready',{method:'POST',body:JSON.stringify(body)});status(readyStatus,'Queued '+data.candidate.repository+' '+data.candidate.head_sha,false);await refresh()}catch(error){status(readyStatus,error.message,true)}});
byId('refresh').addEventListener('click',function(){refresh().catch(function(error){status(readyStatus,error.message,true)})});Array.prototype.forEach.call(document.querySelectorAll('[data-control]'),function(button){button.addEventListener('click',async function(){try{var reason=byId('control-reason').value.trim();if(reason.length<3)throw new Error('Enter an audited reason');var action=button.dataset.control;await request('/deploy/release-bus/'+action,{method:'POST',body:JSON.stringify({scope:button.dataset.scope,reason:reason})});status(byId('control-status'),'Control updated.',false);await refresh()}catch(error){status(byId('control-status'),error.message,true)}})});
if(state.token){connect()}else{status(authStatus,'Paste a GitHub token to continue.',false)}
})();`;
}
