export function renderDeployBusUI(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>6529 Release Bus v2</title><meta name="theme-color" content="#050505">
<style>
*{box-sizing:border-box}body{margin:0;background:#080808;color:#f4f4f5;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:16px}main{max-width:1240px;margin:auto;display:grid;gap:16px}header,.panel{border:1px solid #2d2d30;background:#111113;border-radius:16px;padding:20px}h1,h2,h3{margin:0 0 8px}h1{font-size:25px}h2{font-size:18px}h3{font-size:15px}.muted{color:#a1a1aa}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.three{grid-template-columns:repeat(3,minmax(0,1fr))}.field{display:grid;gap:6px}.wide{grid-column:1/-1}label{font-weight:650}input,select,textarea,button{font:inherit;border-radius:10px}input,select,textarea{width:100%;border:1px solid #3f3f46;background:#09090b;color:#fafafa;padding:10px 12px}textarea{min-height:76px;resize:vertical}:focus-visible{outline:3px solid #60a5fa;outline-offset:2px}.actions,.row{display:flex;gap:8px;flex-wrap:wrap}.actions{margin-top:12px}.header-actions{justify-content:flex-end;margin-top:0}.row{justify-content:space-between;align-items:flex-start}button,a.button{border:1px solid #4b5563;background:#27272a;color:white;padding:8px 12px;text-decoration:none;cursor:pointer}button.primary{background:#2563eb;border-color:#3b82f6}button.danger{background:#7f1d1d;border-color:#ef4444}button:disabled{opacity:.5;cursor:not-allowed}.status{min-height:24px;margin-top:10px}.error{color:#fca5a5}.success{color:#86efac}.warning{color:#fde68a}.cards,.stack{display:grid;gap:10px}.card{border:1px solid #303036;background:#0b0b0d;border-radius:12px;padding:12px}.incident{border-color:#7f1d1d;background:#1c0b0b}.badge{border:1px solid #52525b;border-radius:999px;padding:2px 8px;font-size:12px;white-space:nowrap}.sha{font-family:ui-monospace,monospace;overflow-wrap:anywhere}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:10px 0}.metric{border:1px solid #27272a;border-radius:8px;padding:8px}.metric strong{display:block}.list{margin:6px 0;padding-left:20px}.hidden{display:none!important}@media(max-width:760px){.grid,.three,.metrics{grid-template-columns:1fr}.wide{grid-column:auto}.row{display:grid}.header-actions{justify-content:flex-start}}
</style></head><body><main>
<header><div class="row"><div><h1>Release Bus v2</h1><p class="muted">Separate staging and explicit production queues, exact manifests, and serialized environment ownership.</p></div><div class="actions header-actions"><button id="forget" type="button" class="hidden">Forget token</button><a class="button" href="/deploy/ui">Manual console (OFF only)</a></div></div></header>
<section id="authentication" class="panel" aria-labelledby="authentication-heading"><h2 id="authentication-heading">GitHub authentication</h2><div class="field"><label for="token">GitHub token</label><textarea id="token" autocomplete="off" spellcheck="false" placeholder="Token with repository access"></textarea></div><div class="actions"><button id="connect" class="primary" type="button">Connect</button></div><div id="auth-status" class="status" role="status" aria-live="polite"></div></section>
<div id="authenticated" class="hidden stack">
<section class="panel"><div class="row"><div><h2>Runtime and environment ownership</h2><p class="muted">OFF blocks all reconciliation. Pauses retain exact state. Locks serialize only shared mutation and E2E.</p></div><div class="actions"><button id="reconcile">Reconcile now</button><button id="refresh">Refresh</button></div></div><div id="runtime" class="cards"></div></section>
<section class="panel"><h2>Register exact green PR for staging</h2><form id="register-form"><div class="grid three">
<div class="field"><label for="repository">Repository</label><select id="repository"><option value="frontend">Frontend</option><option value="backend">Backend</option></select></div>
<div class="field"><label for="pr-number">PR number</label><input id="pr-number" type="number" min="1" required></div>
<div class="field"><label for="branch">Branch</label><input id="branch" required pattern="[A-Za-z0-9._/-]+"></div>
<div class="field wide"><label for="sha">Exact head SHA</label><input id="sha" required pattern="[a-fA-F0-9]{40}" maxlength="40" class="sha"></div>
<div id="backend-plan" class="wide hidden"><div class="grid"><div class="field"><label for="units">Backend deploy units</label><textarea id="units" placeholder="dbMigrationsLoop&#10;api"></textarea></div><div class="field"><label for="edges">Unit DAG edges</label><textarea id="edges" placeholder="dbMigrationsLoop -> api"></textarea></div></div></div>
<div class="field wide"><label for="dependencies">Candidate dependencies</label><textarea id="dependencies" placeholder="candidate-uuid:BOTH"></textarea><span class="muted">One candidate UUID plus STAGING, PRODUCTION, or BOTH per line.</span></div>
</div><div class="actions"><button id="resolve" type="button">Resolve current SHA</button><button id="register" class="primary" type="submit">Register for staging</button></div><div id="register-status" class="status" role="status" aria-live="polite"></div></form></section>
<section class="panel"><h2>Staging queue</h2><p class="muted">STAGING_DEPLOYED is visible and distinct from STAGING_VALIDATED.</p><div id="staging-candidates" class="cards"></div></section>
<section class="panel"><h2>Production queue</h2><p class="muted">Only exact STAGING_VALIDATED SHAs can be explicitly opted in.</p><div id="production-candidates" class="cards"></div></section>
<section class="panel"><h2>Active staging, qualification, and production work</h2><div id="active-trains" class="stack"></div></section>
<section class="panel"><h2>Recent trains</h2><div id="trains" class="cards"></div><div id="train-detail" class="stack"></div></section>
<section class="panel"><h2>Exact manifests</h2><div id="manifests" class="cards"></div></section>
<section class="panel"><h2>Operator controls</h2><div class="field"><label for="control-reason">Audited reason</label><input id="control-reason" maxlength="1000"></div><div class="actions"><button data-control="pause" data-scope="ALL" class="danger">Pause all</button><button data-control="pause" data-scope="STAGING">Pause staging</button><button data-control="pause" data-scope="PRODUCTION">Pause production</button><button data-control="resume" data-scope="ALL">Resume all</button><button data-control="resume" data-scope="STAGING">Resume staging</button><button data-control="resume" data-scope="PRODUCTION">Resume production</button></div><div id="control-status" class="status" role="status" aria-live="polite"></div></section>
</div></main><script src="/deploy/ui/bus/app.js" defer></script></body></html>`;
}

export function renderDeployBusUiApp(): string {
  return `'use strict';(function(){
var key='deploy-ui-token';var state={token:localStorage.getItem(key)||'',mode:'OFF'};
var terminal=['STAGING_VALIDATED','PRODUCTION_DEPLOYED','FAILED','CANCELLED'];
var byId=function(id){return document.getElementById(id)};
function setAuthenticatedLayout(isAuthenticated){byId('authentication').classList.toggle('hidden',isAuthenticated);byId('authenticated').classList.toggle('hidden',!isAuthenticated);byId('forget').classList.toggle('hidden',!isAuthenticated)}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function status(node,message,error){node.textContent=message||'';node.className='status '+(error?'error':'success')}
function headers(){return {'Authorization':'Bearer '+state.token,'Content-Type':'application/json'}}
async function request(url,options){var response=await fetch(url,Object.assign({},options||{},{headers:Object.assign({},headers(),options&&options.headers||{})}));var payload=await response.json().catch(function(){return{}});if(!response.ok)throw new Error(payload.error||payload.message||('Request failed ('+response.status+')'));return payload}
function time(value){return Number(value)?new Date(Number(value)).toLocaleString():'Not recorded'}
function duration(start,end){var ms=Math.max(0,(Number(end)||Date.now())-(Number(start)||Date.now())),s=Math.floor(ms/1000),m=Math.floor(s/60),h=Math.floor(m/60);return h?h+'h '+m%60+'m':m?m+'m '+s%60+'s':s+'s'}
function runLink(repository,id){return repository&&/^\\d+$/.test(String(id||''))?'<a class="button" target="_blank" rel="noreferrer" href="https://github.com/6529-Collections/6529seize-'+esc(repository)+'/actions/runs/'+esc(id)+'">Workflow '+esc(id)+'</a>':''}
function parseJson(value){if(!value)return null;if(typeof value==='object')return value;try{return JSON.parse(value)}catch(_){return null}}
function parseDependencies(){return byId('dependencies').value.split(/\\n/).map(function(v){return v.trim()}).filter(Boolean).map(function(line){var parts=line.split(':');if(parts.length!==2)throw new Error('Dependency must be candidate-uuid:ENVIRONMENT');return{candidate_id:parts[0],environment:parts[1].toUpperCase()}})}
function parsePlan(){if(byId('repository').value!=='backend')return null;var units=byId('units').value.split(/\\n|,/).map(function(v){return v.trim()}).filter(Boolean);if(!units.length)throw new Error('At least one backend deploy unit is required');var edges=byId('edges').value.split(/\\n/).map(function(v){return v.trim()}).filter(Boolean).map(function(line){var values=line.split(/\\s*->\\s*/);if(values.length!==2)throw new Error('DAG edge must use A -> B');return values});return{units:units,edges:edges}}
function candidateCard(item){var canMark=item.status==='STAGING_VALIDATED'&&state.mode==='PRODUCTION';var canRevoke=item.status==='READY_FOR_PRODUCTION';var canCancel=['READY_FOR_STAGING','READY_FOR_PRODUCTION','NEEDS_REBASE','WAITING_FOR_DEPENDENCY'].includes(item.status);var actions=(canMark?'<button data-mark="'+esc(item.id)+'" data-sha="'+esc(item.head_sha)+'" data-version="'+esc(item.row_version)+'" class="primary">Mark ready for production</button>':'')+(canRevoke?'<button data-revoke="'+esc(item.id)+'" data-version="'+esc(item.row_version)+'">Revoke readiness</button>':'')+(canCancel?'<button data-cancel="'+esc(item.id)+'" data-version="'+esc(item.row_version)+'" class="danger">Cancel</button>':'');var dependencies=(item.dependencies||[]).map(function(dependency){return '<a class="button" href="#candidate-'+esc(dependency.prerequisite_candidate_id)+'">Requires '+esc(dependency.prerequisite_candidate_id)+' · '+esc(dependency.environment)+'</a>'}).join('');return '<article id="candidate-'+esc(item.id)+'" class="card"><div class="row"><div><strong>'+esc(item.repository)+' PR #'+esc(item.pr_number)+' · '+esc(item.branch_name)+'</strong><div class="sha">'+esc(item.head_sha)+'</div><div class="muted">'+esc(item.hold_reason||'No hold')+'</div><div class="muted">Updated '+esc(time(item.updated_at))+'</div></div><span class="badge">'+esc(item.status)+'</span></div>'+(dependencies?'<div class="actions">'+dependencies+'</div>':'')+(actions?'<div class="actions">'+actions+'</div>':'')+'</article>'}
function bindCandidateActions(){Array.prototype.forEach.call(document.querySelectorAll('[data-mark]'),function(button){button.onclick=async function(){await candidateAction('/deploy/release-bus-v2/candidates/'+encodeURIComponent(button.dataset.mark)+'/mark-ready-for-production',{expected_head_sha:button.dataset.sha,expected_row_version:Number(button.dataset.version)})}});Array.prototype.forEach.call(document.querySelectorAll('[data-revoke]'),function(button){button.onclick=async function(){await candidateAction('/deploy/release-bus-v2/candidates/'+encodeURIComponent(button.dataset.revoke)+'/revoke-production-readiness',{expected_row_version:Number(button.dataset.version)})}});Array.prototype.forEach.call(document.querySelectorAll('[data-cancel]'),function(button){button.onclick=async function(){await candidateAction('/deploy/release-bus-v2/candidates/'+encodeURIComponent(button.dataset.cancel)+'/cancel',{expected_row_version:Number(button.dataset.version)})}})}
async function candidateAction(url,body){try{await request(url,{method:'POST',body:JSON.stringify(body)});await refresh()}catch(error){status(byId('register-status'),error.message,true)}}
function renderCandidates(items){var production=['READY_FOR_PRODUCTION','PRODUCTION_IN_TRAIN','PRODUCTION_BUILDING_OR_QUALIFYING','PRODUCTION_DEPLOYING','PRODUCTION_DEPLOYED'];var prod=items.filter(function(item){return production.includes(item.status)}),staging=items.filter(function(item){return !production.includes(item.status)});byId('staging-candidates').innerHTML=staging.length?staging.map(candidateCard).join(''):'<p class="muted">No staging candidates.</p>';byId('production-candidates').innerHTML=prod.length?prod.map(candidateCard).join(''):'<p class="muted">No explicit production candidates.</p>';bindCandidateActions()}
function renderOperation(item){var result=parseJson(item.result_json),summary=result&&result.summary||{},live=item.workflow_run;var failure=item.failure_class||item.failure_message?'<p class="error"><strong>'+esc(item.failure_class||'FAILURE')+':</strong> '+esc(item.failure_message||'See workflow result')+'</p>':'';var retry=item.status==='RETRY_WAIT'?'<p class="warning">Infrastructure retry '+esc(item.attempt)+'/'+esc(item.max_attempts)+' scheduled '+esc(time(item.next_retry_at))+'. Candidate isolation is not applied.</p>':'';var amber=['PENDING','DISPATCHED','RUNNING'].includes(item.status)?'<p class="warning">'+esc(item.status==='PENDING'?'Awaiting idempotent dispatch':item.status==='DISPATCHED'?'Dispatched; discovering exact workflow run':'Workflow is active or awaiting structured terminal reconciliation')+'</p>':'';var jobs=live?(live.jobs||[]).map(function(job){var active=(job.steps||[]).filter(function(step){return step.status==='in_progress'||step.conclusion==='failure'}).map(function(step){return step.name+' · '+(step.conclusion||step.status)}).join(', ');return '<li><strong>'+esc(job.name)+'</strong> · '+esc(job.conclusion||job.status)+(active?' · '+esc(active):'')+'</li>'}).join(''):'';var observation=item.workflow_observation_error?'<p class="warning">'+esc(item.workflow_observation_error)+'</p>':jobs?'<ul class="list">'+jobs+'</ul>':'';return '<article class="card"><div class="row"><div><strong>'+esc(item.operation_type)+(item.service?' · '+esc(item.service):'')+'</strong><div class="muted">'+esc(item.repository||'control')+' / '+esc(item.environment||'orchestration')+' · attempt '+esc(item.attempt)+'/'+esc(item.max_attempts)+'</div></div><span class="badge">'+esc(item.status)+'</span></div><div class="metrics"><div class="metric"><span class="muted">Elapsed</span><strong>'+esc(duration(item.started_at||item.created_at,item.completed_at))+'</strong></div><div class="metric"><span class="muted">Started</span><strong>'+esc(time(item.started_at||item.created_at))+'</strong></div><div class="metric"><span class="muted">Expected SHA</span><strong class="sha">'+esc(item.expected_sha||'n/a')+'</strong></div><div class="metric"><span class="muted">Artifact</span><strong class="sha">'+esc(item.artifact_digest||summary.artifact_digest||'pending')+'</strong></div></div>'+amber+retry+failure+observation+'<div class="actions">'+runLink(item.repository,item.external_id)+'</div></article>'}
function renderTrainDetail(data){var train=data.train;return '<article class="card"><div class="row"><div><h3>'+esc(train.lane)+' · '+esc(train.status)+'</h3><div class="sha">'+esc(train.id)+'</div></div><span class="badge">'+esc(duration(train.created_at,train.completed_at))+'</span></div><div class="metrics"><div class="metric"><span class="muted">Phase elapsed</span><strong>'+esc(duration(train.phase_started_at))+'</strong></div><div class="metric"><span class="muted">Frontend SHA</span><strong class="sha">'+esc(train.frontend_composed_sha||train.frontend_base_sha||'n/a')+'</strong></div><div class="metric"><span class="muted">Backend SHA</span><strong class="sha">'+esc(train.backend_composed_sha||train.backend_base_sha||'n/a')+'</strong></div><div class="metric"><span class="muted">Manifest</span><strong>'+esc(train.manifest_id||'pending')+'</strong></div></div>'+(train.failure_message?'<p class="error"><strong>'+esc(train.failure_class)+':</strong> '+esc(train.failure_message)+'</p>':'')+'<p class="muted">'+esc(train.recovery_message||'Exact state is reconciling idempotently.')+'</p></article>'+(data.operations||[]).map(renderOperation).join('')+'<article class="card"><h3>Durable events</h3><ul class="list">'+(data.events||[]).map(function(event){return '<li>'+esc(time(event.created_at))+' · '+esc(event.event_type)+'</li>'}).join('')+'</ul></article>'}
function renderTrains(items,details){var active=items.filter(function(item){return !terminal.includes(item.status)});byId('active-trains').innerHTML=active.length?active.map(function(item){return details[item.id]?renderTrainDetail(details[item.id]):'<p class="muted">Loading '+esc(item.id)+'</p>'}).join(''):'<p class="muted">No active train owns staging or production.</p>';byId('trains').innerHTML=items.length?items.map(function(item){return '<article class="card"><div class="row"><div><strong>'+esc(item.lane)+' train</strong><div class="sha">'+esc(item.id)+'</div><div class="muted">Created '+esc(time(item.created_at))+' · '+esc(duration(item.created_at,item.completed_at))+'</div></div><div><span class="badge">'+esc(item.status)+'</span> <button data-train="'+esc(item.id)+'">Details</button></div></div></article>'}).join(''):'<p class="muted">No trains recorded.</p>';Array.prototype.forEach.call(document.querySelectorAll('[data-train]'),function(button){button.onclick=async function(){try{byId('train-detail').innerHTML=renderTrainDetail(await request('/deploy/release-bus-v2/trains/'+encodeURIComponent(button.dataset.train)))}catch(error){byId('train-detail').innerHTML='<p class="error">'+esc(error.message)+'</p>'}}})}
function renderManifests(items){byId('manifests').innerHTML=items.length?items.map(function(item){var exact=item.status==='STAGING_DEPLOYED'?'<p class="warning">Deployed, but E2E validation is not complete.</p>':item.status==='STAGING_VALIDATED'?'<p class="success">Exact release set passed staging E2E. Production remains explicit.</p>':'';return '<article class="card"><div class="row"><div><strong>'+esc(item.lane)+' manifest</strong><div class="sha">'+esc(item.id)+' · '+esc(item.identity_sha256)+'</div></div><span class="badge">'+esc(item.status)+'</span></div>'+exact+'<div class="metrics"><div class="metric"><span class="muted">Frontend</span><strong class="sha">'+esc(item.frontend_sha||'n/a')+'</strong></div><div class="metric"><span class="muted">Backend</span><strong class="sha">'+esc(item.backend_sha||'n/a')+'</strong></div><div class="metric"><span class="muted">Deployed</span><strong>'+esc(time(item.deployed_at))+'</strong></div><div class="metric"><span class="muted">Validated</span><strong>'+esc(time(item.validated_at))+'</strong></div></div>'+runLink('frontend',item.e2e_run_id)+'</article>'}).join(''):'<p class="muted">No exact manifests yet.</p>'}
function renderRuntime(data){state.mode=data.mode;var maintenance=data.mode==='OFF'?'<article class="card warning"><strong>Maintenance/manual fallback active.</strong> V2 cannot claim or advance work while OFF. Serialize shared refs and deployments using the linked fallback console.</article>':'';var controls=(data.controls||[]).map(function(item){return '<article class="card"><div class="row"><strong>'+esc(item.scope)+'</strong><span class="badge">'+(item.paused?'PAUSED':'RUNNING')+'</span></div><div class="muted">'+esc(item.reason||'No pause reason')+'</div></article>'}).join('');var locks=(data.locks||[]).map(function(item){var owned=item.owner_train_id&&Number(item.expires_at)>Date.now();return '<article class="card"><div class="row"><strong>'+esc(item.name)+'</strong><span class="badge">'+(owned?'OWNED':'FREE')+'</span></div><div class="sha">'+esc(item.owner_train_id||'No owner')+'</div><div class="muted">Lease expiry '+esc(time(item.expires_at))+'</div></article>'}).join('');byId('runtime').innerHTML=maintenance+'<p><span class="badge">Mode '+esc(data.mode)+'</span></p>'+controls+locks;byId('register').disabled=data.mode==='OFF';byId('reconcile').disabled=data.mode==='OFF'}
async function refresh(){var all=await Promise.all([request('/deploy/release-bus-v2/candidates?limit=100'),request('/deploy/release-bus-v2/trains'),request('/deploy/release-bus-v2/manifests'),request('/deploy/release-bus-v2/controls')]);var details={};await Promise.all((all[1].trains||[]).filter(function(item){return !terminal.includes(item.status)}).map(async function(item){details[item.id]=await request('/deploy/release-bus-v2/trains/'+encodeURIComponent(item.id))}));renderRuntime(all[3]);renderCandidates(all[0].candidates||[]);renderTrains(all[1].trains||[],details);renderManifests(all[2].manifests||[])}
async function connect(){var moveFocus=document.activeElement===byId('connect');state.token=(byId('token').value||state.token).trim();if(!state.token){status(byId('auth-status'),'Paste a token first.',true);return}var session;try{session=await request('/deploy/ui/session')}catch(error){localStorage.removeItem(key);state.token='';setAuthenticatedLayout(false);status(byId('auth-status'),error.message,true);return}localStorage.setItem(key,state.token);byId('token').value='';status(byId('auth-status'),'Authenticated as '+session.login,false);setAuthenticatedLayout(true);if(moveFocus)byId('forget').focus();try{await refresh()}catch(error){status(byId('register-status'),error.message,true)}}
byId('connect').onclick=connect;byId('forget').onclick=function(){localStorage.removeItem(key);state.token='';setAuthenticatedLayout(false);status(byId('auth-status'),'Token removed.',false);byId('token').focus()};byId('refresh').onclick=function(){refresh().catch(function(error){status(byId('register-status'),error.message,true)})};byId('reconcile').onclick=async function(){try{await request('/deploy/release-bus-v2/reconcile',{method:'POST',body:'{}'});await refresh()}catch(error){status(byId('register-status'),error.message,true)}};byId('repository').onchange=function(){byId('backend-plan').classList.toggle('hidden',byId('repository').value!=='backend')};
byId('resolve').onclick=async function(){try{var repository=byId('repository').value,branch=byId('branch').value.trim();if(!branch)throw new Error('Enter a branch first');var data=await request('/deploy/ui/branch-head?repository='+encodeURIComponent(repository)+'&branch='+encodeURIComponent(branch));byId('sha').value=data.head_sha;status(byId('register-status'),'Resolved '+data.head_sha,false)}catch(error){status(byId('register-status'),error.message,true)}};
byId('register-form').onsubmit=async function(event){event.preventDefault();try{var body={repository:byId('repository').value,pr_number:Number(byId('pr-number').value),branch_name:byId('branch').value.trim(),expected_head_sha:byId('sha').value.trim().toLowerCase(),deploy_plan:parsePlan(),dependencies:parseDependencies()};var data=await request('/deploy/release-bus-v2/candidates',{method:'POST',body:JSON.stringify(body)});status(byId('register-status'),'Queued exact '+data.candidate.head_sha+' for staging.',false);await refresh()}catch(error){status(byId('register-status'),error.message,true)}};
Array.prototype.forEach.call(document.querySelectorAll('[data-control]'),function(button){button.onclick=async function(){try{var reason=byId('control-reason').value.trim();if(reason.length<3)throw new Error('Enter an audited reason');await request('/deploy/release-bus-v2/'+button.dataset.control,{method:'POST',body:JSON.stringify({scope:button.dataset.scope,reason:reason})});status(byId('control-status'),'Control updated.',false);await refresh()}catch(error){status(byId('control-status'),error.message,true)}}});
if(state.token){connect()}else{status(byId('auth-status'),'Paste a GitHub token to continue.',false)}
})();`;
}
