export const DISTRIBUTION_PHASE_AIRDROP = 'Airdrop';
export const DISTRIBUTION_PHASE_AIRDROP_ARTIST = 'Airdrop - Artist';
export const DISTRIBUTION_PHASE_AIRDROP_TEAM = 'Airdrop - Team';

export const DISTRIBUTION_AUTOMATIC_AIRDROP_PHASES = [
  DISTRIBUTION_PHASE_AIRDROP,
  DISTRIBUTION_PHASE_AIRDROP_ARTIST,
  DISTRIBUTION_PHASE_AIRDROP_TEAM
] as const;
