name: Deploy overRatesRevocationLoop to PRODUCTION

on: workflow_dispatch

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: Build
        run: pushd src/overRatesRevocationLoop && npm run build && popd
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        run: pushd src/overRatesRevocationLoop && npm run sls-deploy:prod && popd
      - name: Notify about failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          title: "Seize PROD overRatesRevocationLoop DEPLOY: CI pipeline is broken!!!"
          description: ${{ env.COMMIT_SHA }} - ${{ env.COMMIT_MESSAGE }}
          content: "@everyone"
          color: 0xff0000

      - name: Notify about success
        uses: sarisia/actions-status-discord@v1
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          title: "Seize PROD overRatesRevocationLoop DEPLOY: CI pipeline complete"
          description: ${{ env.COMMIT_SHA }} - ${{ env.COMMIT_MESSAGE }}
          color: 0x00ff00