name: Deploy overvotesRevocationLoop to PRODUCTION

on: workflow_dispatch

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: Build
        run: pushd src/overvotesRevocationLoop && npm run build && popd
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        run: pushd src/overvotesRevocationLoop && npm run sls-deploy:prod && popd