name: tdhHistoryLoop deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name (staging or prod)'
        required: true
        default: 'staging'
      branch:
        description: 'Branch name'
        required: true
        default: 'main'

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Install dependencies
        run: npm i
      - name: Build
        run: pushd src/tdhHistoryLoop && npm run build && popd
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: pushd src/tdhHistoryLoop && npm run sls-deploy:${{ github.event.inputs.environment }} && popd
      - name: Notify about failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          title: Seize ${{ github.event.inputs.environment }} tdhHistoryLoop DEPLOY CI pipeline is broken!!!
          description: Branch ${{ github.event.inputs.branch }} - Version ${{ env.COMMIT_SHA }} - ${{ env.COMMIT_MESSAGE }}
          content: "@everyone"
          color: 0xff0000

      - name: Notify about success
        uses: sarisia/actions-status-discord@v1
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          title: Seize ${{ github.event.inputs.environment }} tdhHistoryLoop DEPLOY CI pipeline complete
          description: Branch ${{ github.event.inputs.branch }} - Version ${{ env.COMMIT_SHA }} - ${{ env.COMMIT_MESSAGE }}
          color: 0x00ff00